name: OpenCore
version: 0.1
main: com.illusioncis7.opencore.OpenCore
api-version: 1.21
softdepend: [Plan]
commands:
  suggest:
    description: Submit a configuration suggestion
  suggestions:
    description: List open suggestions
  vote:
    description: Vote on a suggestion
  rules:
    description: List server rules
  rollbackconfig:
    description: Roll back a configuration change
  myrep:
    description: Show your reputation
  gptlog:
    description: Show recent GPT responses
  repinfo:
    description: Show reputation info for a player
