name: OpenCore
version: 0.1
main: com.illusioncis7.opencore.OpenCore
api-version: 1.21
softdepend: [Plan]
commands:
  suggest:
    description: Submit a configuration suggestion
  suggestions:
    description: List open suggestions
  vote:
    description: Manage votes
  rules:
    description: List server rules
