name: OpenCore
version: 0.1
main: com.illusioncis7.opencore.OpenCore
api-version: 1.21
softdepend: [Plan]
commands:
  opencore:
    description: Root command for OpenCore
    aliases: [oc]
    permission: opencore.command.opencore
