name: OpenCore
version: 0.1
main: com.illusioncis7.opencore.OpenCore
api-version: 1.21
commands:
  gpttest:
    description: Testet den GPT-Service
  opencorereload:
    description: Lädt die OpenCore-Konfiguration neu
