name: OpenCore
version: 0.1
main: com.illusioncis7.opencore.OpenCore
api-version: 1.21
softdepend: [Plan]
commands:
  suggest:
    description: Submit a configuration suggestion
  suggestions:
    description: List open suggestions
  vote:
    description: Vote on a suggestion
  rules:
    description: List server rules
  rollbackconfig:
    description: Roll back a configuration change
  myrep:
    description: Show your reputation
  gptlog:
    description: Show recent GPT responses
  repinfo:
    description: Show reputation info for a player
  repchange:
    description: Show details for a reputation change event
  status:
    description: Show plugin status
  configlist:
    description: List configurable parameters
  votestatus:
    description: Show closed vote results
  editrule:
    description: Edit an existing rule
  rulehistory:
    description: Show history for a rule
  chatflags:
    description: Manage chat reputation flags
  reload:
    description: Reload plugin configuration
